[2024-03-29T20:41:27.497+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_test00.transform_data manual__2024-03-29T20:41:23.876180+00:00 [queued]>
[2024-03-29T20:41:27.505+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_test00.transform_data manual__2024-03-29T20:41:23.876180+00:00 [queued]>
[2024-03-29T20:41:27.505+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-29T20:41:27.544+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): transform_data> on 2024-03-29 20:41:23.876180+00:00
[2024-03-29T20:41:27.550+0000] {standard_task_runner.py:60} INFO - Started process 1694 to run task
[2024-03-29T20:41:27.551+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'spotify_test00', 'transform_data', 'manual__2024-03-29T20:41:23.876180+00:00', '--job-id', '165', '--raw', '--subdir', 'DAGS_FOLDER/dag_spotify_test.py', '--cfg-path', '/tmp/tmpoluckf1y']
[2024-03-29T20:41:27.553+0000] {standard_task_runner.py:88} INFO - Job 165: Subtask transform_data
[2024-03-29T20:41:27.587+0000] {task_command.py:423} INFO - Running <TaskInstance: spotify_test00.transform_data manual__2024-03-29T20:41:23.876180+00:00 [running]> on host 5eb6f8f434b5
[2024-03-29T20:41:27.656+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spotify_test00' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2024-03-29T20:41:23.876180+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-29T20:41:23.876180+00:00'
[2024-03-29T20:41:27.668+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/usr/local/airflow/src/main.py", line 25, in transform_api
    top10 = transform_json_top10("Gojira", songs)
  File "/usr/local/airflow/src/resources/process.py", line 7, in transform_json_top10
    artist_name = artist['name']
TypeError: string indices must be integers
[2024-03-29T20:41:27.675+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=spotify_test00, task_id=transform_data, execution_date=20240329T204123, start_date=20240329T204127, end_date=20240329T204127
[2024-03-29T20:41:27.700+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 165 for task transform_data (string indices must be integers; 1694)
[2024-03-29T20:41:27.724+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-29T20:41:27.736+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
